title: Louis Royer’s blog
author:
  name: Louis Royer
  email: 55180044+louisroyer@users.noreply.github.com
description: >
  Personal blog

show_excerpts: true
header_pages:
  - categories.md
  - feed.rss

baseurl: ""
url: "https://louisroyer.github.io"
github_username: louisroyer

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%Y-%m-%d"
