title: "Louis Royer’s blog"
copyright: "CC-0 1.0"
show_excerpts: true
url: "https://louisroyer.github.io"
description: >
  Personal blog

author:
  name: "Louis Royer"
  email: "infos.louis.royer@gmail.com"
minima:
  date_format: "%Y-%m-%d"
  social_links:
    github: "louisroyer"
feed:
  categories:
    - tutorial
plugins:
  - "jekyll-feed"
  - "jekyll-sitemap"
  - "jekyll-remote-theme"
remote_theme: "jekyll/minima"

