title: "Louis Royer’s blog"

# minima 2.x
author: "Louis Royer"
email: "55180044+louisroyer@users.noreply.github.com"
rss: "rss"
# minima 3.x
#author:
#  name: "Louis Royer"
#  email: "55180044+louisroyer@users.noreply.github.com"

description: >
  Personal blog

show_excerpts: true

baseurl: ""
url: "https://louisroyer.github.io"
github_username: "louisroyer"

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - "categories.md"

theme: "minima"
plugins:
  - "jekyll-feed"
